edmcouncil/idmp

ISO/ISO11238-RegistrationAuthorities.rdf
ISO/ISO11238-Substances.rdf
ISO/ISO11240-UnitsOfMeasurement.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/ISO21090-HarmonizedDatatypes.rdf
META/ChangeManagement.rdf
META/ISOConformanceAnnotations.rdf

Description: Modified the maturity level of all IDMP ontologies that are considered 'release' to Release and updated a couple of the others to revise their metadata as appropriate

IDMP-GitHub-MaturityAlignment - Maturity Levels to About File Contents Alignment

---

etc/onto-viewer-web-app/config/groups_config.yaml

Signed-off-by: Patrycja Miazek <patrycja.miazek@makolab.com>

Update config file

---

CMNS/AnnotationVocabulary.rdf
CMNS/Classifiers.rdf
CMNS/CodesAndCodeSets.rdf
CMNS/Collections.rdf
CMNS/ContextualDesignators.rdf
CMNS/ContextualIdentifiers.rdf
CMNS/DatesAndTimes.rdf
CMNS/Designators.rdf
CMNS/Identifiers.rdf
CMNS/TextDatatype.rdf

Description: Revise the Commons Ontology Library to reflect the revisions made in by the finalization task force for the 1.0 release at OMG

IDMP-CMNS-1.0 - Revise the Commons Ontology Library per OMG updates

---

AboutIDMPDev.rdf
AboutIDMPProd.rdf
CMNS/AboutCommons.rdf
CMNS/MetadataCMNS.rdf
CMNS/Organizations.rdf
CMNS/PartiesAndSituations.rdf
CMNS/ProductsAndServices.rdf
CMNS/catalog-v001.xml
catalog-v001.xml

Description:
1. Added a new organizations ontology to Commons, derived from FIBO, to support definitions such as those required to implement a GTIN
2. Added concepts defining certain GS1 organization-related terminology including a GTIN to the products and services ontology
3. Added the new organizations ontology to the various load and catalog files

IDMP-326 - Add the concept of a Global Trade Item Number (GTIN)

---

etc/transformation/GSRS/gsrs-public-data-identifiers.rqg

cc: @Heiner-Oberkampf @oleksandrsnizhko @mereolog 
Please review.
As I still don't have push access directly to the repo, I am creating the PR from the fork.

IDMP-235: Fix ChemblDatabase URI

---

etc/transformation/GSRS/transform-local.sh

@Heiner-Oberkampf @mereolog @oleksandrsnizhko 
Small fix to the GSRS script, please review.

Fix GSRS script for result generation

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
EXT/Examples/TerlipressinExample.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/catalog-v001.xml

Description: Added packaged medicinal product, including related concepts for container, package item, and other containers, as well as batch and batch identifier

IDMP-366: Add RIM related IDMP concept: Packaged Medicinal Product

---

.gitignore
etc/transformation/GSRS/README.md
etc/transformation/GSRS/_common.sh
etc/transformation/GSRS/transform-accurids.sh
etc/transformation/GSRS/transform-local.sh
etc/transformation/SPOR/README.md
etc/transformation/SPOR/substances/README.md
etc/transformation/SPOR/substances/spor-substances.rqg
etc/transformation/SPOR/substances/transform-local.sh
etc/transformation/_env.sh
etc/transformation/_sparql_generate.sh

@Heiner-Oberkampf @oleksandrsnizhko Please review

IDMP-312: Add SPOR Substances Transformation

---

LCC/MetadataLCC.rdf
etc/onto-viewer-web-app/config/ontology_config.yaml

Signed-off-by: mereolog <pawel.garbacz@makolab.com>
Fixes: #251

New about and metadata files

---

etc/transformation/SPOR/organisations/README.md
etc/transformation/SPOR/organisations/spor-organisations.rqg
etc/transformation/SPOR/organisations/transform-local.sh

IDMP-350: Add SPOR OMS Transformation

---

etc/transformation/SPOR/substances/spor-substances.rqg

Adjust transformation for SPOR SMS

---

etc/testing/hygiene_parameterized/testHygiene_reporting_iso_conformance.sparql

Signed-off-by: mereolog <pawel.garbacz@makolab.com>
Fixes: #269

IDMP-348 - ISO conformance report as a hygiene test

---

EXT/Examples/catalog-v001.xml

This removes an obsolete line in [catalog-v001.xml](https://github.com/edmcouncil/idmp/blob/master/EXT/Examples/catalog-v001.xml).

Update catalog-v001.xml to fix an obsolete Locations.rdf resolution

---

ISO/ISO11615-MedicinalProducts.rdf

Description: Extend the medicinal products ontology to include a number of bridge concepts required for UC-2, CQ-1, including process, process step, batch, lot, and a number of subordinate concepts and related identifiers. Note that this is likely incomplete, with more details required as the competency questions for this use case evolve, but it covers a number of existing gaps.

IDMP-387 - Complete the set of terms required to answer UC-2, CQ-1

---

ISO/ISO11238-Substances.rdf

added definitions for 
cis, trans, absolute, achiral and mixed
mixed needs clarification with IDMP, the usage is not clear from the TS

IDMP-243 - stereochemisty

---

ISO/ISO11238-Substances.rdf

Description: add missing notes for structure, molecular structure, and stereochemistry per issue #284.

IDMP-GitHub-284 - Notes on certain classes for structure, molecular structure, and stereochemistry are needed

---

ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf

Revised approach to controlled vocabularies in SPOR RMS and added a controlled vocab for marketing status for SPOR

IDMP-398 - Add concept for Marketing Status (SPOR RMS)

---

etc/transformation/SPOR/organisations/README.md

Add more cleanup instructions for SPOR OMS transformation

---

etc/transformation/SPOR/organisations/spor-organisations.rqg

Update SPOR OMS Transformation

---

etc/transformation/GSRS/gsrs-public-data-identifiers.rqg
etc/transformation/GSRS/gsrs-public-data-relationships.rqg
etc/transformation/SPOR/substances/spor-substances.rqg

IDMP-385: Update URI pattern

---

etc/transformation/SPOR/referentials/README.md
etc/transformation/SPOR/referentials/spor-referentials.rqg
etc/transformation/SPOR/referentials/transform-local.sh

IDMP-393 & IDMP-408: Add SPOR RMS Transformation

---

ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: 
1. initial commit to incorporate specified substance groups 1-4

IDMP-435 - Create classes for SSG1, SSG2, SSG3, SSG4

---

AboutIDMPDev-ReferenceIndividuals.rdf
AboutIDMPDev.rdf
AboutIDMPProd-ReferenceIndividuals.rdf
AboutIDMPProd.rdf
CMNS/QuantitiesAndUnits.rdf
ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: 
1. added package identifier and its constituents in support of UC-2
2. revised the inheritance structure for a packaged medicinal product
3. fleshed out the definition of an MPID based on its component structure from ISO 11615
4. augmented the model to better reflect the various roles that a package item can play and integrate additional packaging concepts

IDMP-465 - Integrate revised manufactured item and packaging strategy for UC-2

---

CMNS/AboutCommons-ReferenceIndividuals.rdf
CMNS/AboutCommons.rdf
CMNS/MetadataCMNS.rdf
CMNS/StructuredCollections.rdf
CMNS/catalog-v001.xml

Description: 
1. Created an initial version of a structured collections ontology and added it to the various metadata files for CMNS
2. Modified the definition of 'set' to include the word 'distinct', which is not present in the ISO definition

IDMP-512 - Need the concept of an ordered collection to define polymers

---

ISO/ISO11238-RegistrationAuthorities.rdf

Description: In the ontology, revised the registration authorities ontology to distinguish FDA 'active moiety' exclusivity from patent exclusivity

IDMP-514 - Review and Correct the target role for GSRS "Active Moiety (Exclusivity)" used in Aripiprazole Lauroxil

---

ISO/ISO11238-Substances.rdf

Description: Added missing restrictions for moiety name and moiety identifier to the moiety class

IDMP-510 - Moiety has no restrictions for "moiety identifier" and "moiety name"

---

ISO/ISO11238-Substances.rdf
ISO/ISO11239-PharmaceuticalDoseForms.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/ISO11616-PharmaceuticalProducts.rdf

Description: preliminary addition of content related to dose forms

IDMP-531 - Add concepts for WHO case/demo e.g., release characteristics

---

etc/transformation/GSRS/gsrs-public-data-relationships.rqg

Fix https://github.com/edmcouncil/idmp/issues/308

GSRS: Avoid obsolete triples

---

CMNS/ProductsAndServices.rdf

Description: Revised definitions and sources in the Products and Services ontology (CMNS) to correspond with the latest GS1 specification and to add sources such as the OECD where available.

IDMP-527 - Revise the CMNS/ProductsAndServices ontology to reflect the latest discussions with GS1

---

EXT/Examples/AmlodipineExample.rdf
ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf

The resolution to this issue augments the substance ontology with the content covered in Figure 15 of ISO 11238 for substance modifications as requested in IDMP-540

IDMP-540 - Complete the set of optional fields from Annex L: for Substance and Chemical Substance for Modification (Figure 15)

---

ISO/ISO11615-MedicinalProducts.rdf

Description: Clarified the definition of marketing authorization holder and marketing authorization holder identifier per the issue request

IDMP-395 - Check definition for 'marketing authorization holder'

---

EXT/Examples/AmlodipineExample.rdf
etc/CQ/Example/uc3_cq1-1.sparql

corrected MedDRA medical condition classes to use OWL restrictions instead of object property isIdentifiedBy to reference the MedDRA ID

IDMP-581 The MedDRA individuals for the Amlodipine Example cause punning

---

ISO/ISO11238-Substances.rdf

Description: Corrected declarations for modification method types that caused punning in the substances ontology

Legal punning in d9ececf commit in master

---

ISO/ISO11615-MedicinalProducts.rdf

Description: Add restrictions on medicinal product and authorized medicinal product to better connect them for query writing

IDMP-550 - Document the modelling pattern for Marketing Authorization

---

etc/onto-viewer-web-app/config/label_config.yaml
etc/onto-viewer-web-app/config/search_config.yaml

After ongoing development of the IDMP ontology we need to update the IDMP viewer config.

Update of IDMP viewer config

---

ISO/ISO11615-MedicinalProducts.rdf

Description: loosened a constraint on ingredient with respect to manufactured item per SME request

IDMP-602 - Loosen the restriction on ingredient to say that it -may- be manifested in a manufactured item

---

.gitignore
EXT/Examples/AmlodipineExample.rdf
EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
EXT/Examples/QlairaExample.rdf
EXT/Examples/QlairaExample.ttl
EXT/Examples/TerlipressinExample.rdf

Description: Added disclaimer regarding the content stating that is strictly an example and that some data may be made up for demonstration purposes

IDMP-601 - Add a disclaimer to example ontologies

---

EXT/Examples/TerlipressinExample.rdf

Description: added indications with text from national agencies (UK, NL, SE) for terlipressin medicinal products and mapped to MedDRA

IDMP-605 - Add indications for multiple jurisdictions for terlipressin medicinal products mapped to MedDRA

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/TerlipressinExample.rdf
etc/CQ/Example/uc1_cq3-1.sparql
etc/CQ/Example/uc1_cq3.sparql
etc/unit_tests/cq_expected_results/IDMP/uc1_cq3_amlodipine_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc1_cq3_terlipressin_expected_results.json

Description: 
1. Additions to the Amlodipine example to cover the latest approach to reference substance / reference strength
2. Additions and a few revisions to the Terlipressin example to reflect the latest approach to reference substance / reference strength and to address simplifications that were incorrect (e.g. replacing hasActiveIngredient with hasIngredient)

IDMP-420 - Update Terlipressin Example for reference strength

---

etc/transformation/SPOR/organisations/spor-organisations.rqg

Update spor-organisations.rqg for ORG-code property

---

etc/testing/hygiene_parameterized/testHygiene_deprecated.sparql

owl:sameAs added to ignored properties of test for deprecated properties

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/TerlipressinExample.rdf
ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf

Description:
add oral use as route of administration for Norvask pharmaceutical product (Amlodipine example)
add intravenous use as route of adminstration for Terlipressin pharmaceutical product
add terms reference to SPOR RMS

IDMP-618 Augment Example Data for UC3 CQ 3

---

ISO/ISO11615-MedicinalProducts.rdf

Description:
* added other therapy specifics, therapy, therapy relationship, medication and some classifiers for these
* added relations and properties

IDMP-639 added other therapy specifics related

---

ISO/ISO11615-MedicinalProducts.rdf

fix bug in MedicinalProducts ontology

fix owl:class to owl:Class

---

etc/CQ/Example/uc1_cq3-1.sparql
etc/unit_tests/cq_expected_results/IDMP/uc1_cq3-1_amlodipine_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc1_cq3-1_terlipressin_expected_results.json

Fix to some typos in unit tests

---

ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf

Description: added a complete concept for SPOR term description and revised property hasSPORTermDescription to be an object property accordingly

IDMP-GitHub-465 - idmp-spor:hasSPORTermDescription is language dependent

---

.github/workflows/unit_tests_run.yml

This adds a parameter to GSRS action so that GSRS cache can be rebuild on request.

Update unit_tests_run.yml to orchestrate cache rebuild

---

ISO/MedicalDictionaryForRegulatoryActivities.rdf

Description: fix namespace of registered identifier

GitHub-478 fix namespace

---

ISO/ISO11615-MedicinalProducts.rdf

Description: revised time period associated with shelf life to be a duration rather than date period

hasShelfLifeTimePeriod should expect a cmns-dt:Duration instead of cmns-dt:DatePeriod for medicinal products

---

ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
ISO/ISO11238-RegistrationAuthorities.rdf
ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/ISO21090-HarmonizedDatatypes.rdf
ISO/NorthAmericanJurisdiction/NorthAmericanRegistrationAuthorities.rdf

This PR fixes some, but not all, spelling typos - for the rest, we need to discuss some more.

Some spelling typos fixed

---

EXT/Examples/TerlipressinExample.rdf

Description: added Sun Pharmaceutical Industries as a manufacturer of terlipressin acetate SUN to address hygiene issues

IDMP-662 - Revise the Terlipressin example to address hygiene issues

---

ISO/ISO11238-Substances.rdf

Description: filled in missing substance name classifier definitions

GitHub-511 - dmp-sub:SubstanceNameClassifier-CommonName has incomplete definition

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/QlairaExample.rdf
EXT/Examples/QlairaExample.ttl

Description: added classifies to SKUs

GitHub-505 - Non-classifying, but just denoting, classifiers

---

ISO/ISO11615-MedicinalProducts.rdf

Description: eliminated default ingredient role codes on ingredient and inactive ingredient

IDMP-634 - Remove the default code for ingredient and active ingredient

---

ISO/ISO11238-Substances.rdf

Description: Revised the substances ontology to include some of the details needed to represent mixtures:
Added mixture type as a classifier and a new boolean property indicating whether or not the mixture is a multi-substance starting material, including restrictions on mixture to connect them

IDMP-675 - Complete the minimal set of required fields from Annex L for Mixtures

---

ISO/ISO11615-MedicinalProducts.rdf

description: change rdfs:range to rdfs:domain ShelfLife for idmp-mprd:hasSpecialStorageConditions and update definition

GitHub-512 -  idmp-mprd:hasSpecialStorageConditions has wrong range

---

etc/testing/spelling/onto_spellchecker.py

Spellcheck is now aware of reified languages, i.e., it takes into account the mvf:hasLanguage property.

Spellcheck ignores reified languages

---

ISO/ISO11238-Substances.rdf

Description: 
Update the ISO 11283 ontology  for conformance points, clean up definitions and annotations as appropriate

IDMP-322 - ISO11238: Document the ISO IDMP conformance level as annotations in the IDMP-O where deviations exist

---

ISO/ISO11615-MedicinalProducts.rdf

Description: Addressed case issue in subClass axiom

IDMP-GitHub-561 - addressed case issue in subClass axiom

---

ISO/ISO11615-MedicinalProducts.rdf

Description: corrected spelling error in subPropertyOf

IDMP-GitHub-567 - Two typos in reference to rdfs:subPropertyOf

---

etc/testing/hygiene_parameterized/testHygiene_single_preflabels.sparql
etc/testing/hygiene_parameterized/testHygiene_unique_preflabels.sparql

This adds new hygiene tests, which are needed because of https://github.com/edmcouncil/idmp/pull/570.

hygiene tests added for prefLabels

---

CMNS/Locations.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: Addressed remaining broken URIs as follows: 
1. resolved an additional poorly formed URI in medicinal products
2. addressed a few more that we have control over in IDMP-O and draft Commons ontologies

GitHub-587 - "Broken" URLs in IDMPO literals

---

ISO/ISO11615-MedicinalProducts.rdf

Description:  Corrected restrictions on age classifier to make more sense and eliminate an apparent circularity

IDMP-682 - Investigate simplifying potential circularity in population characteristic

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/QlairaExample.rdf
ISO/ISO11239-PharmaceuticalDoseForms.rdf
ISO/ISO11615-MedicinalProducts.rdf
etc/CQ/Example/uc2_cq1b.sparql

Description:
1. Added a new class for container role
2. Modified existing container roles to be named individuals rather than classes
3. Updated examples accordingly
4. Modified SPARQL query for UC2 CQ1b to reflect revised pattern to correct a misspelling

IDMP-748 - Modify the packaging approach to make package roles individuals

---

ISO/ISO11615-MedicinalProducts.rdf

Description: 
1. Added marketing status start/stop dates and refined a few related definitions based on the terms and definitions in the ISO standard
2. Adjusted restrictions related to country and jurisdiction, and added risk of supply related attributes, completing the set of attributes for marketing status
3. Added properties and restrictions for legal grounds to marketing status reasons
4. Added properties and restrictions for conditions for marketing authorization or marketing restoration to marketing status reasons
5. Added geographic region for action taken and normalized restrictions, completing the detail required for representation of all attributes in Figure 7 of ISO 11615
6. Added optional change request organization type code and related restriction

IDMP-750 - Complete the work required to fill in marketing status related attributes (EMA-PMS)

---

ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf
etc/CQ/Example/uc3_cq2.sparql
etc/unit_tests/cq_expected_results/IDMP/uc3_cq2_expected_results.json

Description: Completed details for the EudraVigilenceCode, including is registered by and other required values

IDMP-753 - xEVMPD code class definition check

---

CMNS/QuantitiesAndUnits.rdf

Description: This update adds the concept of a measurement reference, which corresponds to recommendations needed to align with SysML as well as other NIST / ESA recommendations

IDMP-771 - Revise the Quantities and Units ontology to reflect the latest revisions in the OMG Commons library

---

ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf

Description: corrected punning issue with respect to SPOR-related scheme definitions

GitHub-626 - Address punning in SPOR schema definitions for RMS, PMS

---

ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf

Description: corrected punning issue related to SPOR-Domain

GitHub-629 - Punning of idmp-spor:SPOR-Domain

---

etc/testing/hygiene_parameterized/testHygiene_classes_used_as_individuals_in_owl_punning.sparql
etc/testing/hygiene_parameterized/testHygiene_classes_used_as_individuals_punning.sparql
etc/testing/hygiene_parameterized/testHygiene_individuals_used_as_classes_punning.sparql

This pr adds a couple of checks to warn about punning of classes and individuals.

Checks for punning on classes and individuals

---

EXT/Examples/TerlipressinExample.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: 
1. IDMP-776 - Renamed Concentration to ConcentrationStrength, per request, for consistency
2. IDMP-777 - Added a restriction connecting packaged medicinal product with marketing status and revised the definition accordingly

IDMP-776 - Harmonize Strength naming: Change "Concentration" to "Concentration Strength"

---

etc/CQ/Example/uc2_cq2-1.sparql
etc/CQ/Example/uc_cmc_cq2.sparql
etc/CQ/Example/uc_cmc_cq3.sparql
etc/CQ/Example/uc_cmc_cq4.sparql
etc/CQ/Example/uc_cmc_cq5.sparql
etc/CQ/Example/uc_cmc_cq6.sparql
etc/unit_tests/configs/idmp_tests_config.yaml
etc/unit_tests/cq_expected_results/IDMP/uc2_cq2-1_amlodipine_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc3_cq3_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc_cmc_cq2_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc_cmc_cq4_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc_cmc_cq5_expected_results.json
etc/unit_tests/cq_expected_results/IDMP/uc_cmc_cq6_expected_results.json
etc/unit_tests/cq_expected_results/uc_cmc_cq2_expected_results.json

These two updates should correct two of four failing regression tests in hygiene testing

Updated 2 of the CMC UC CQs to reflect ontology revisions
