edmcouncil/idmp

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/EuropeanUnionClinicalTrialsRegister.rdf
EXT/Examples/TerlipressinExample.rdf
ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/ISO11616-PharmaceuticalProducts.rdf
META/ISOConformanceAnnotations.rdf
etc/CQ/Example/cq7.sparql
etc/CQ/cq7.sparql

This resolution makes the following updates to the released, provisional, and informative ontologies:
1. Adds a distinct conformance level for name and annotations, including the definition, in contrast with naming conformance, which means that the concept has the same name as something in an ISO standard but not the same meaning.
2. Renames IngredientRole to Ingredient, including its subclasses ('active ingredient role' --> 'active ingredient', 'inactive ingredient role' --> 'inactive ingredient', 'adjuvant role' --> adjuvant, 'excipient role' --> excipient) and deprecates the original classes, making them equivalent to the new ones
3. Updates the examples that were impacted accordingly

IDMP-298 - Rename IngredientRole to Ingredient, including its subclasses

---

ISO/ISO11238-Substances.rdf

Description: 
In order to address this, this resolution adds the definition of matter and a new property, hasSubstanceName, to better conform with the semantics required by the ISO IDMP standards. Having said this, from a chemistry perspective, it is the structure that is essential (which we made someValuesFrom rather than min 0) to defining a substance, not its name. Thus the relationship between a substance and its name is min 0 in the ontology. This also facilitates mapping to resources that may not include the substance name.

IDMP-GitHub-228 - Nameless substances

---

ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf

Description: Corrected versionIRI on European Registration Authorities ontology

IDMP-GitHub-249 - Wrong versionIRI in ISO/EuropeanJurisdiction/EuropeanRegistrationAuthorities.rdf

---

ISO/MetadataISO.rdf

This hot-fix adds missing imports to the [MetadataISO](https://github.com/edmcouncil/idmp/blob/master/ISO/MetadataISO.rdf) ontology.

Update MetadataISO with missing import statements

---

CMNS/ProductsAndServices.rdf

Description: extended the products and services ontology to include stock keeping unit (SKU) and uniform product code (UPC) in response to the requirements of UC-2

IDMP-367 - Include SKUs in IDMP-O

---

ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf
META/ISOConformanceAnnotations.rdf

Description: 
(1) augmented the conformance annotations to include extension and needs clarification as triggers for reviewers of the IDMP ISO standards to consider as part of their review process; 
(2) revised the names of the individuals to include the prefix that distinguishes these from other concepts of conformance in the IDMP standards; 
(3) updated the ISO ontologies as appropriate to reflect these changes

IDMP-390 - Add annotations to suggest changes to definitions that are needed in the IDMP standard

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/TerlipressinExample.rdf
ISO/ISO11238-Substances.rdf

Description: This resolution moves certain characteristics of a substance that were originally modeled as properties of molecular structure to being properties of the moiety or chemical substance directly and revised examples accordingly, and adds conformance updates to moiety and chemical substance, as the model no longer conforms to the ISO standard precisely. It also changes the class hierarchy with respect to structural representation, making it a subclass of designation, which is a better fit, and which at least partially addresses issues #241, 243, and 266.

IDMP-391 - The relationship between structure and structural representation should be better defined

---

ISO/ISO11238-Substances.rdf

Description: In order to simplify the possible approaches suggested in the issue, we have relaxed the restriction on the property hasStructure with respect to substances, single substances, and moieties to optional from at most one value, to allow for cases where there may be multiples, especially if mapping content from multiple repositories. This is not identical to how single substances are modeled with respect to their relationship with respect to Figure 10 in the ISO 11238 standard, which says that there is at most one structure associated with a single substance, but is needed to support the data in some cases.

single substance has max 1 molecular structure is wrong

---

etc/testing/hygiene_parameterized/testHygiene_reporting_iso_conformance.sparql

Signed-off-by: mereolog <pawel.garbacz@makolab.com>
This replaces the wrong property in the conformance level check with the proper one, i.e., idmp-cmpl:hasConformanceToISOLevel.

Fix to ISO conformance level test

---

ISO/ISO11239-PharmaceuticalDoseForms.rdf

Description: Added two properties - hasReleaseCharactic and hasBasicDoseForm to support the WHO demonstration

IDMP-549 - Augment the definition of pharmaceutical dose form with two additional properties

---

ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: Added classes for all ingredient roles specified in Table D.1 of the ISO/TS 20443 implementation guide with the exception of  'ingredient not otherwise specified', for which Ingredient, or InactiveIngredient should be used. 
Any mapping that includes 'ingredient not otherwise specified' should be mapped to 'ingredient', which has been assigned the 'INGR' code in the ontology.

IDMP-304 - Complete the set of roles corresponding to the table in ISO/TS 20443, pages 112-113 (ingredient roles)

---

ISO/ISO11239-PharmaceuticalDoseForms.rdf

Description: 
1. Augmented the pharmaceutical dose forms ontology to include transformation and the property, hasTransformationProcedure to support  the WHO demo
2. Added a restriction to connect a pharmaceutical dose form to a relevant transformation

IDMP-541 - Connect Manufactured Item and Pharmaceutical Product via Transformation

---

AboutIDMPDev-ReferenceIndividuals.rdf
AboutIDMPDev.rdf
AboutIDMPProd-ReferenceIndividuals.rdf
AboutIDMPProd.rdf
CMNS/AboutCommons-ReferenceIndividuals.rdf
CMNS/AboutCommons.rdf
CMNS/MetadataCMNS.rdf
CMNS/QuantitiesAndUnits.rdf
CMNS/RegistrationAuthorities.rdf
CMNS/StatisticalMeasures.rdf
CMNS/catalog-v001.xml
EXT/Examples/AmlodipineExample.rdf
ISO/ISO11238-RegistrationAuthorities.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/ISO11616-PharmaceuticalProducts.rdf
catalog-v001.xml

Description: This resolution augments the ontology to include therapeutic indications (with all elements of that class on Figure 14 in the ISO 11615 standard) and contraindications (again with all elements of that class on Figure 14 in the ISO 11615 standard as well as updates the Amlodipine example. Other concepts required to complete the details presented in Figure 14 for clinical particulars will be covered as required by use cases.

IDMP-561 - Augment the IDMP ontologies to cover therapeutic indications

---

etc/CQ/Example/uc2_cq1.sparql
etc/unit_tests/configs/idmp_tests_config.yaml
etc/unit_tests/cq_expected_results/IDMP/uc2_cq1_amlodipine_expected_results.json

Results of IDMP-599:
UC1-CQ8 ( Investigational Medicinal Products ) Missing Example data in amlodipine. ( TBD in IDMP-610)
UC2-CQ1 Sparql and unit tests missing amlodipine.  ( This Pull Request)

IDMP-599 Adding UC2-CQ1 Amlodipine to sparql and unit tests.

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/TerlipressinExample.rdf
ISO/ISO11238-Substances-DeprecatedElements.rdf
ISO/ISO11238-Substances.rdf
etc/CQ/Example/uc1_cq9.sparql
etc/transformation/GSRS/gsrs-public-data-substances.rqg

Description: Changed the class and property for SimplifiedMolecularInputLineEntry to SMILES and deprecated the originals throughout per SME request

GitHub-278 - hasSimplifiedMolecularInputLineEntrySpecification is misleading and inconsistent

---

AboutIDMPDev-ReferenceIndividuals.rdf
AboutIDMPDev.rdf
AboutIDMPProd-ReferenceIndividuals.rdf
AboutIDMPProd.rdf
ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf
ISO/ISO21090-HarmonizedDatatypes.rdf
MVF/AboutMVF.rdf
MVF/ISO1087-TerminologyScience.rdf
MVF/ISO1087-VocabularyForTermsAndDefinitions.rdf
MVF/MVFtoSKOSMapping.rdf
MVF/MetadataMVF.rdf
MVF/MultipleVocabularyFacility.rdf
MVF/catalog-v001.xml
MetadataIDMP.rdf
catalog-v001.xml

Description: 
1. Add the OMG formal standard ontologies for Multiple Vocabulary Facility to the iDMP GitHub for use as needed for representation of controlled vocabularies
2. Augmented the substances ontology to use the new pattern for controlled vocabularies
3. Augment any concept in the substances ontology that has a datatype code of CD to be a subclass of concept descriptor
4. Augment any concept in the medicinal products ontology that has a datatype code of CD to be a subclass of concept descriptor
5. Fill in missing details for concept descriptors as appropriate (only for those we've already covered)

IDMP-533 - Provide alignment/mapping for ISO "codedConcept" to the target IDMP-O Pattern for Reference Code Lists

---

CMNS/RegistrationAuthorities.rdf

Description: eliminated the symmetric declaration on designates to address reasoning issue

GitHub-434 - cmns-ra:designates is equivalent to cmns-ra:isDesignatedBy

---

ISO/ISO11615-MedicinalProducts.rdf

Description: Revised the definition of product role to allow it to be played by either a product or product specification (similar to the union on its subclass of authorized medicinal product), which addresses some of the issues uncovered in #399

IDMP-633 - The definition of product role is too narrow

---

ISO/ISO11238-Substances.rdf
ISO/ISO21090-HarmonizedDatatypes.rdf

Description: Extended the kinds of structural representations available to include molfile, InChI, and InChIKey with various options for inclusion (as simple properties or as individuals in the case of InChI and InChIKey), and as an individual for molfile to include a URL and version information

IDMP-636 - Extend the concept of structural representation in the ISO 11238 substances ontology to include molfile

---

ISO/ISO11238-Substances.rdf

Description: 
1. Added metadata to nucleic acid substance, added nucleic acid sequence type per the ISO specification
2. Added nucleic acid subunit and related properties and restrictions on both nucleic acid and subunit
3. Added sugar and linkage, and built up the relevant attributes to complete the representation

IDMP-592 - Complete the preliminary modeling work required for Nucleic Acid, covering all detail provided in ISO 11238

---

EXT/Examples/AmlodipineExample.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: add package item type as classifier for package items

IDMP-638 add package item type

---

ISO/ISO11615-MedicinalProducts.rdf

Description: Revised the inheritance for Batch and Lot to subclass constituent rather than product

IDMP-632 - Batch should be a subclass of Constituent rather than Product

---

EXT/Examples/AmlodipineExample.rdf

Definition: cleaned up leftover detail in the Amlodipine example not needed to elucidate the simple case, and that could cause circular reasoning issues, and addressed a wrong reference for the defining molecular formula by moiety

IDMP-661 - Revise the Amlodipine example to match the current patterns for strength and reference strength

---

AboutIDMPDev.rdf

Description: added the MedDRA ontology to the IDMPDev about file since the common terminology for adverse events ontology depends on it and is in AboutDev

AboutIDMPDev-ReferenceIndividuals.rdf alignment with AboutIDMPDev.rdf

---

ISO/EuropeanJurisdiction/SubstancesProductsOrganisationsReferentials.rdf

description: fixed idmp-spor:hasSPORTermDescription to be an owl:ObjectProperty instead of an owl:DatatypeProperty

GitHub-525 - hasSPORTermDescription is an ObjectProperty

---

ISO/ISO11615-MedicinalProducts.rdf
ISO/MedicalDictionaryForRegulatoryActivities.rdf

Description: adjusted the definition of packaged medicinal product and added a restriction for its identifier, adjusted the definition of undesirable effect (which was originally quoted from the 11615 ISO standard but was circular, and the definition in the MedDRA ontology of system organ class to comply with our policies for good definitions.

GitHub-501 - ISO non-compliant definitions

---

ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description: 
1. Cleaned up conformance level for ingredients in the substances ontology after review of ISO 11615; added conformance levels and regularized the modeling of age as a population characteristic, with conformance details in the medicinal products ontology
2. Additional refinement of annotations related to medicinal
products, including elements related to administrable dose forms and authorized medicinal products
3. Added annotations for a number of additional concepts and cleaned up the model in a few cases, such as for batch, clinical trial, and gender related elements
4. Added notes regarding controlled vocabularies not specified in the IDMP standard and extensions to the definition of interaction
5. Extended definitions of medicinal product header, manufacturing …

IDMP-383 - ISO11615: Document the ISO IDMP conformance level as annotations in the IDMP-O where deviations exist

---

EXT/Examples/AmlodipineExample.rdf
EXT/Examples/QlairaExample.rdf
ISO/ISO11615-MedicinalProducts.rdf

summary: used 'is characterized by package item/manufactured item' instead of 'is played by' to link the package item constituent to the contained type

IDMP-657 - add missing package item properties

---

ISO/ISO11238-Substances.rdf

Description: extended (completed) the details of Figure 16 in ISO 11238 to relate a target to the corresponding organism and type, now that organism and its classifiiers are included in the substances ontology

IDMP-713a - Augment the ontology to incorporate additional information related to biologics

---

ISO/ISO11615-MedicinalProducts.rdf

1. Cleaned up and completed definitions related to contraindications, therapeutic indications and population characteristics as related to a medicinal product based on SME feedback
2. Completed the definition of pharmaceutical product characteristic
3. Added manufactured item quantity; made packaged medicinal product a direct subclass of product specification rather than of medicinal product; added missing restrictions to packaged medicinal product and manufactured item
4. Fleshed out the definition of package item, including quantity and other missing restrictions
5. Added missing definition for a code for the combined pharmaceutical dose form and related restrictions on medicinal product
6. Added other missing attributes of medicinal product, such as pediatric use indicator, added …

IDMP-726 - Augment / revise the ontology to cover gaps w.r.t. ISO 11615 for UC4

---

ISO/ISO11238-Substances.rdf

Description: Revised the prefix in the definition of reference source document for reference source to correct an error

IDMP-GitHub-573 - Correct a wrong prefix for reference source

---

CMNS/ProductsAndServices.rdf
CMNS/RegulatoryAgencies.rdf

Added two properties, isProvidedTo and isIssuedTo in order to simplify restrictions in the regulatory agencies ontology and make it more amenable to mapping to BFO

IDMP-GitHub-571 - Simplify the licensing definitions in Commons to facilitate mapping to BFO

---

MVF/MultipleVocabularyFacility.rdf

Description: Loosen constraints on MVFElement to allow MEDdra and EMA SPOR terms to be mapped using owl:sameAs. Note that this change was made in the OMG GitHub for MVF and brought over from there.

IDMP-GitHub-584 - Loosen constraints on MVF Element to allow for mapping MEDdra terms to those in EMA SPOR and other vocabularies

---

CMNS/QuantitiesAndUnits.rdf

Description: 
1. Removed unnecessary (and circular) restrictions from the Commons quantities and units ontology (the other two are definitional and min 0)
2. Reviewed the "circular" definition in MVF, which is optional (min 0 and definitional), and needs to remain in the ontology.
3. Reviewed the two restrictions on ConceptDescriptor - these are also optional and definitional, and should remain in the ontology.
4. Issues with the current model for basic and pharmaceutical dose form will be addressed in a separate resolution, as they require additional work to clean up and augment the model to better reflect the details provided in ISO 11239. See https://dil-edmcouncil.atlassian.net/browse/IDMP-739.
5. Reviewed the restrictions on MedicinalProductAuthorization and …

GitHub-577 - Potentially vicious "circular" restrictions

---

SPAR/po.rdf

Description: eliminated references to swrl:builtin, which not all reasoners handle properly

GitHub-601 - Modify the SPAR PO ontology to eliminate the SWRL Builtin statements which cannot be processed by certain reasoners

---

ISO/ISO11238-Substances.rdf

Description: increased the max cardinality on the property 'has quantity value range' on amount to allow for cases where there is both a quantity value range and reference range

GitHub-598 - Obsolete restriction on idmp-sub:Amount

---

ISO/ISO11238-Substances.rdf
ISO/ISO11615-MedicinalProducts.rdf

Description:
1. Augmented the definition of manufacturing or business operation to include the classifier for type of operation
2. Added connections between the manufacturing authorization and the manufacturing or business operation as well as to the medicinal product
3. Expanded the notion of a manufacturing authorization to allow for parts of a medicinal product (i.e., manufactured items)
4. Added several property chains connecting manufacturers , facilities (manufacturing or business operations), sites, connecting products to the sites and facilities that produce them, and so forth
5. cleaned up certain restrictions related to manufacturers, linked them to the legal entities (organizations) that play them, added the notion of a confidentiality indicator, including the classifier, …

IDMP-779 - Augment the ISO 11615 ontology to include a property chain from manufacturer to the manufacturing site
